USE [master]
GO
/****** Object:  Database [TodoFrenosDB]    Script Date: 23/5/2024 15:27:28 ******/
CREATE DATABASE [TodoFrenosDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TodoFrenosDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\TodoFrenosDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TodoFrenosDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\TodoFrenosDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [TodoFrenosDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TodoFrenosDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TodoFrenosDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TodoFrenosDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TodoFrenosDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TodoFrenosDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TodoFrenosDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [TodoFrenosDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TodoFrenosDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TodoFrenosDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TodoFrenosDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TodoFrenosDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TodoFrenosDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TodoFrenosDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TodoFrenosDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TodoFrenosDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TodoFrenosDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [TodoFrenosDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TodoFrenosDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TodoFrenosDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TodoFrenosDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TodoFrenosDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TodoFrenosDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TodoFrenosDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TodoFrenosDB] SET RECOVERY FULL 
GO
ALTER DATABASE [TodoFrenosDB] SET  MULTI_USER 
GO
ALTER DATABASE [TodoFrenosDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TodoFrenosDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TodoFrenosDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TodoFrenosDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TodoFrenosDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TodoFrenosDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'TodoFrenosDB', N'ON'
GO
ALTER DATABASE [TodoFrenosDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [TodoFrenosDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [TodoFrenosDB]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 23/5/2024 15:27:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Appointments]    Script Date: 23/5/2024 15:27:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Appointments](
	[AppointId] [bigint] IDENTITY(1,1) NOT NULL,
	[UserID] [bigint] NULL,
	[VehicleId] [bigint] NULL,
	[AppointDate] [date] NULL,
	[AppointCreationDate] [datetime] NULL,
	[AppointModifyDate] [datetime] NULL,
	[Reason] [nvarchar](255) NULL,
	[AppointState] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[AppointId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Categories]    Script Date: 23/5/2024 15:27:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categories](
	[CategoryId] [bigint] IDENTITY(1,1) NOT NULL,
	[CategoryName] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CategoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[InvoiceDetail]    Script Date: 23/5/2024 15:27:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[InvoiceDetail](
	[DetailId] [bigint] IDENTITY(1,1) NOT NULL,
	[MasterId] [bigint] NOT NULL,
	[ProductId] [bigint] NOT NULL,
	[Stock] [int] NOT NULL,
	[Price] [decimal](18, 2) NOT NULL,
	[SubTotal] [decimal](18, 2) NOT NULL,
	[Taxes] [decimal](18, 2) NOT NULL,
	[Total] [decimal](18, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[DetailId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[InvoiceMaster]    Script Date: 23/5/2024 15:27:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[InvoiceMaster](
	[MasterId] [bigint] IDENTITY(1,1) NOT NULL,
	[UserId] [bigint] NOT NULL,
	[DatePurchase] [datetime] NOT NULL,
	[SubTotal] [decimal](18, 2) NOT NULL,
	[Taxes] [decimal](18, 2) NOT NULL,
	[Total] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_InvoiceMaster] PRIMARY KEY CLUSTERED 
(
	[MasterId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Products]    Script Date: 23/5/2024 15:27:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[ProductId] [bigint] IDENTITY(1,1) NOT NULL,
	[CategoryId] [bigint] NULL,
	[ProductName] [nvarchar](100) NULL,
	[URL_Image] [nvarchar](max) NULL,
	[Stock] [int] NULL,
	[Price] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[ProductId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Roles]    Script Date: 23/5/2024 15:27:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[RolId] [bigint] IDENTITY(1,1) NOT NULL,
	[RolName] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RolId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ShoppingCart]    Script Date: 23/5/2024 15:27:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ShoppingCart](
	[CartId] [bigint] IDENTITY(1,1) NOT NULL,
	[UserId] [bigint] NULL,
	[ProductId] [bigint] NULL,
	[DateCart] [datetime] NULL,
	[Stock] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[CartId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserRol]    Script Date: 23/5/2024 15:27:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserRol](
	[UserId] [bigint] NOT NULL,
	[RolId] [bigint] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 23/5/2024 15:27:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserId] [bigint] IDENTITY(1,1) NOT NULL,
	[UserName] [nvarchar](100) NOT NULL,
	[LastName] [nvarchar](100) NOT NULL,
	[SecondSurname] [nvarchar](100) NOT NULL,
	[Age] [int] NOT NULL,
	[Email] [nvarchar](255) NOT NULL,
	[PasswordHash] [nvarchar](255) NOT NULL,
	[PhoneNumber] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Vehicles]    Script Date: 23/5/2024 15:27:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Vehicles](
	[VehicleId] [bigint] IDENTITY(1,1) NOT NULL,
	[UserId] [bigint] NULL,
	[Brand] [nvarchar](50) NULL,
	[RegistrationCar] [nvarchar](20) NULL,
	[CreationDate] [datetime] NULL,
	[CarState] [int] NULL,
 CONSTRAINT [PK_Vehicles] PRIMARY KEY CLUSTERED 
(
	[VehicleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Appointments]  WITH CHECK ADD  CONSTRAINT [Fk_Apponint_UserID] FOREIGN KEY([UserID])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[Appointments] CHECK CONSTRAINT [Fk_Apponint_UserID]
GO
ALTER TABLE [dbo].[Appointments]  WITH CHECK ADD  CONSTRAINT [Fk_Apponint_VehicleId] FOREIGN KEY([VehicleId])
REFERENCES [dbo].[Vehicles] ([VehicleId])
GO
ALTER TABLE [dbo].[Appointments] CHECK CONSTRAINT [Fk_Apponint_VehicleId]
GO
ALTER TABLE [dbo].[InvoiceDetail]  WITH CHECK ADD  CONSTRAINT [Fk_Details_MasterId] FOREIGN KEY([MasterId])
REFERENCES [dbo].[InvoiceMaster] ([MasterId])
GO
ALTER TABLE [dbo].[InvoiceDetail] CHECK CONSTRAINT [Fk_Details_MasterId]
GO
ALTER TABLE [dbo].[InvoiceDetail]  WITH CHECK ADD  CONSTRAINT [Fk_Details_ProductId] FOREIGN KEY([ProductId])
REFERENCES [dbo].[Products] ([ProductId])
GO
ALTER TABLE [dbo].[InvoiceDetail] CHECK CONSTRAINT [Fk_Details_ProductId]
GO
ALTER TABLE [dbo].[InvoiceMaster]  WITH CHECK ADD  CONSTRAINT [Fk_Invoice_UserID] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[InvoiceMaster] CHECK CONSTRAINT [Fk_Invoice_UserID]
GO
ALTER TABLE [dbo].[Products]  WITH CHECK ADD  CONSTRAINT [Fk_CategoryId] FOREIGN KEY([CategoryId])
REFERENCES [dbo].[Categories] ([CategoryId])
GO
ALTER TABLE [dbo].[Products] CHECK CONSTRAINT [Fk_CategoryId]
GO
ALTER TABLE [dbo].[ShoppingCart]  WITH CHECK ADD  CONSTRAINT [Fk_Cart_ProductId] FOREIGN KEY([ProductId])
REFERENCES [dbo].[Products] ([ProductId])
GO
ALTER TABLE [dbo].[ShoppingCart] CHECK CONSTRAINT [Fk_Cart_ProductId]
GO
ALTER TABLE [dbo].[ShoppingCart]  WITH CHECK ADD  CONSTRAINT [Fk_Cart_UserID] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[ShoppingCart] CHECK CONSTRAINT [Fk_Cart_UserID]
GO
ALTER TABLE [dbo].[UserRol]  WITH CHECK ADD  CONSTRAINT [Fk_RolId] FOREIGN KEY([RolId])
REFERENCES [dbo].[Roles] ([RolId])
GO
ALTER TABLE [dbo].[UserRol] CHECK CONSTRAINT [Fk_RolId]
GO
ALTER TABLE [dbo].[UserRol]  WITH CHECK ADD  CONSTRAINT [Fk_UserID] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[UserRol] CHECK CONSTRAINT [Fk_UserID]
GO
USE [master]
GO
ALTER DATABASE [TodoFrenosDB] SET  READ_WRITE 
GO
